M48
; DRILL file {KiCad 7.0.2} date Wed May 24 22:35:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-24T22:35:43+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.067
%
G90
G05
T1
X105.29Y-83.99
X111.07Y-83.99
T2
X148.76Y-76.234
X148.76Y-78.266
X153.84Y-77.25
T0
M30
